# Base https://gist.github.com/suggoitanoshi/8aa4eccc0b1df4ca63a01beceb65546a
# For home use, you don't need to edit anymore.
version: '3'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  grasscutter:
    image: siakbary/dockergc:alpine-Patch-2.7-Early
    command: -d 'mongodb://mongodb:27017' -b '2.0.0.100' -g '2.0.0.100' -f 'yes'
    restart: unless-stopped
    volumes:
      - resources:/home/Grasscutter/resources
    ports:
      - "22102:22102/udp"
      - "443:443/tcp"
      - "80:80/tcp"
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
volumes:
 data:
 resources: