name: DockerGC Alpine (2.7)
on:
  push:
    paths:
    - 'gc/os_alpine'
    - 'gc/VERSION_GC_Patch-2.7'
    - '.github/workflows/DockerGC_alpine_2.7.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git rm -f --ignore-unmatch gc/Grasscutter_Resources && git submodule update --init --depth=1 --recursive
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
       distribution: temurin
       java-version: '17'
    - name: Cache gradle files
      uses: actions/cache@v2
      with:
       path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
        ./.gradle/loom-cache
       key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle.properties', '**/*.accesswidener') }}
       restore-keys: |
        ${{ runner.os }}-gradle-
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker image
      run: cd gc && chmod +x run.sh && sh run.sh alpine build 2
    - name: Push Docker image
      run: cd gc && sh run.sh alpine push 2
    - name: Tar Folder Work
      run: cd gc && tar -cvf dockergc.tar work
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
       name: DockerGC
       path: dockergc.tar