name: DockerGC Alpine (2.7)
on:
  push:
    paths:
    - 'gc/os_alpine'
    - 'gc/VERSION_GC_Patch-2.7'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git rm -f --ignore-unmatch gc/Grasscutter_Resources && git submodule update --init --depth=1 --recursive
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
       distribution: temurin
       java-version: '17'
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker image
      run: cd gc && chmod +x run.sh && sh run.sh ubuntu build 2
    - name: Push Docker image
      run: cd gc && sh run.sh ubuntu push 2